function xnext = state_eq(xnow,u,t_delta,Cn,a_R1,a_C1)
    soc=xnow(1);
    beta2=xnow(4);
    beta3=xnow(5);

    soc_poly = [soc^5;soc^4;soc^3;soc^2;soc;1];

    R1 = beta2 + a_R1 * soc_poly;
    C1 = beta3 + a_C1 * soc_poly;
    tau = R1*C1;

    xnext = [1,0,0,0,0;...
                0,exp(-t_delta/tau),0,0,0;...
                0,0,1,0,0;...
                0,0,0,1,0;...
                0,0,0,0,1] * xnow + ...
                ...
             [-t_delta/Cn;...
              R1*(1-exp(-t_delta/tau));0;0;0] * u;
end